import type { PublicKey } from 'paillier-bigint';
import type { KeyShare } from './key-share';
import type { ThresholdKeyConfig } from './threshold-key-config';

/**
 * A complete threshold key pair with all shares.
 *
 * Generated by ThresholdKeyGenerator and contains the public key
 * for encryption plus all key shares for distribution to Guardians.
 */
export interface ThresholdKeyPair {
  /** Standard Paillier public key for encryption */
  readonly publicKey: PublicKey;
  /** Verification keys for each share (for ZK proof verification) */
  readonly verificationKeys: readonly Uint8Array[];
  /** The n key shares to distribute to Guardians */
  readonly keyShares: readonly KeyShare[];
  /** Threshold configuration */
  readonly config: ThresholdKeyConfig;
  /**
   * Precomputed decryption constant: θ = L(g^(4·Δ·λ) mod n²) mod n
   *
   * Used by the DecryptionCombiner to convert the combined partial
   * decryptions into the final plaintext: m = L(combined) · θ⁻¹ mod n.
   *
   * This value is public and safe to distribute — it reveals no information
   * about the private key λ.
   */
  readonly theta: bigint;
}
