
export enum EciesStringKey {
  Error_ECIESError_InvalidECIESMultipleEncryptedKeySize = 'Error_ECIESError_InvalidECIESMultipleEncryptedKeySize',
  Error_ECIESError_InvalidECIESPublicKeyLength = 'Error_ECIESError_InvalidECIESPublicKeyLength',
  Error_ECIESError_InvalidECIESMultipleRecipientCountSize = 'Error_ECIESError_InvalidECIESMultipleRecipientCountSize',
  Error_ECIESError_InvalidECIESMultipleDataLengthSize = 'Error_ECIESError_InvalidECIESMultipleDataLengthSize',
  Error_ECIESError_InvalidECIESMultipleRecipientIdSize = 'Error_ECIESError_InvalidECIESMultipleRecipientIdSize',
  Error_ECIESError_CRCError = 'Error_ECIESError_CRCError',
  Error_ECIESError_InvalidEncryptionType = 'Error_ECIESError_InvalidEncryptionType',
  Error_ECIESError_InvalidIVLength = 'Error_ECIESError_InvalidIVLength',
  Error_ECIESError_InvalidAuthTagLength = 'Error_ECIESError_InvalidAuthTagLength',
  Error_ECIESError_InvalidHeaderLength = 'Error_ECIESError_InvalidHeaderLength',
  Error_ECIESError_InvalidDataLength = 'Error_ECIESError_InvalidDataLength',
  Error_ECIESError_InvalidEncryptedDataLength = 'Error_ECIESError_InvalidEncryptedDataLength',
  Error_ECIESError_InvalidMessageCrc = 'Error_ECIESError_InvalidMessageCrc',
  Error_ECIESError_InvalidMnemonic = 'Error_ECIESError_InvalidMnemonic',
  Error_ECIESError_InvalidOperation = 'Error_ECIESError_InvalidOperation',
  Error_ECIESError_MessageLengthMismatch = 'Error_ECIESError_MessageLengthMismatch',
  Error_ECIESError_InvalidEncryptedKeyLength = 'Error_ECIESError_InvalidEncryptedKeyLength',
  Error_ECIESError_InvalidEphemeralPublicKey = 'Error_ECIESError_InvalidEphemeralPublicKey',
  Error_ECIESError_RecipientNotFound = 'Error_ECIESError_RecipientNotFound',
  Error_ECIESError_InvalidSignature = 'Error_ECIESError_InvalidSignature',
  Error_ECIESError_InvalidSenderPublicKey = 'Error_ECIESError_InvalidSenderPublicKey',
  Error_ECIESError_TooManyRecipients = 'Error_ECIESError_TooManyRecipients',
  Error_ECIESError_PrivateKeyNotLoaded = 'Error_ECIESError_PrivateKeyNotLoaded',
  Error_ECIESError_RecipientKeyCountMismatch = 'Error_ECIESError_RecipientKeyCountMismatch',
  Error_ECIESError_InvalidRecipientCount = 'Error_ECIESError_InvalidRecipientCount',
  Error_ECIESError_FileSizeTooLarge = 'Error_ECIESError_FileSizeTooLarge',
  Error_ECIESError_DecryptionFailed = 'Error_ECIESError_DecryptionFailed',
  Error_ECIESError_InvalidRecipientPublicKey = 'Error_ECIESError_InvalidRecipientPublicKey',
  Error_ECIESError_SecretComputationFailed = 'Error_ECIESError_SecretComputationFailed',

  // Member Error Types - buildReasonMap(MemberErrorType, 'Error', 'MemberError')
  Error_MemberError_MissingMemberName = 'Error_MemberError_MissingMemberName',
  Error_MemberError_InvalidMemberNameWhitespace = 'Error_MemberError_InvalidMemberNameWhitespace',
  Error_MemberError_InvalidEmail = 'Error_MemberError_InvalidEmail',
  Error_MemberError_InvalidMemberName = 'Error_MemberError_InvalidMemberName',
  Error_MemberError_MissingEmail = 'Error_MemberError_MissingEmail',
  Error_MemberError_InvalidEmailWhitespace = 'Error_MemberError_InvalidEmailWhitespace',
  Error_MemberError_MissingPrivateKey = 'Error_MemberError_MissingPrivateKey',
  Error_MemberError_NoWallet = 'Error_MemberError_NoWallet',
  Error_MemberError_WalletAlreadyLoaded = 'Error_MemberError_WalletAlreadyLoaded',
  Error_MemberError_InvalidMnemonic = 'Error_MemberError_InvalidMnemonic',
  Error_MemberError_IncorrectOrInvalidPrivateKey = 'Error_MemberError_IncorrectOrInvalidPrivateKey',
  Error_MemberError_MemberNotFound = 'Error_MemberError_MemberNotFound',
  Error_MemberError_MemberAlreadyExists = 'Error_MemberError_MemberAlreadyExists',
  Error_MemberError_InvalidMemberStatus = 'Error_MemberError_InvalidMemberStatus',
  Error_MemberError_FailedToHydrateMember = 'Error_MemberError_FailedToHydrateMember',
  Error_MemberError_InvalidMemberData = 'Error_MemberError_InvalidMemberData',
  Error_MemberError_FailedToConvertMemberData = 'Error_MemberError_FailedToConvertMemberData',
  Error_MemberError_MissingEncryptionData = 'Error_MemberError_MissingEncryptionData',
  Error_MemberError_EncryptionDataTooLarge = 'Error_MemberError_EncryptionDataTooLarge',
  Error_MemberError_InvalidEncryptionData = 'Error_MemberError_InvalidEncryptionData',

  // GUID Error Types - buildReasonMap(GuidErrorType, 'Error', 'GuidError')
  Error_GuidError_Invalid = 'Error_GuidError_Invalid',
  Error_GuidError_InvalidWithGuidTemplate = 'Error_GuidError_InvalidWithGuidTemplate',
  Error_GuidError_UnknownBrandTemplate = 'Error_GuidError_UnknownBrandTemplate',
  Error_GuidError_UnknownLengthTemplate = 'Error_GuidError_UnknownLengthTemplate',

  // Length Error Types - buildReasonMap(LengthErrorType, 'Error', 'LengthError')
  Error_LengthError_LengthIsTooShort = 'Error_LengthError_LengthIsTooShort',
  Error_LengthError_LengthIsTooLong = 'Error_LengthError_LengthIsTooLong',
  Error_LengthError_LengthIsInvalidType = 'Error_LengthError_LengthIsInvalidType',

  // PBKDF2 Error Types - buildReasonMap(Pbkdf2ErrorType, 'Error', 'Pbkdf2Error')
  Error_Pbkdf2Error_InvalidProfile = 'Error_Pbkdf2Error_InvalidProfile',
  Error_Pbkdf2Error_InvalidSaltLength = 'Error_Pbkdf2Error_InvalidSaltLength',
  Error_Pbkdf2Error_InvalidHashLength = 'Error_Pbkdf2Error_InvalidHashLength',

  // Secure Storage Error Types - buildReasonMap(SecureStorageErrorType, 'Error', 'SecureStorageError')
  Error_SecureStorageError_DecryptedValueLengthMismatch = 'Error_SecureStorageError_DecryptedValueLengthMismatch',
  Error_SecureStorageError_DecryptedValueChecksumMismatch = 'Error_SecureStorageError_DecryptedValueChecksumMismatch',
  Error_SecureStorageError_ValueIsNull = 'Error_SecureStorageError_ValueIsNull',

  Error_InvalidEmailError_Invalid = 'Error_InvalidEmailError_Invalid',
  Error_Utils_EncryptionFailedNoAuthTag = 'Error_Utils_EncryptionFailedNoAuthTag',
  Error_PasswordLoginError_FailedToStoreLoginData = 'Error_PasswordLoginError_FailedToStoreLoginData',
  Error_PasswordLoginError_PasswordLoginNotSetUp = 'Error_PasswordLoginError_PasswordLoginNotSetUp',
}
